### ISSUE TITLE
Crash during stitching when processing constant data.

### ISSUE THREAD

**Issue by cristianberneanu** [diffix/syndiffix#106]
```py
>>> Synthesizer(pandas.DataFrame(numpy.ones((2,200)))).sample()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python310\lib\site-packages\syndiffix\synthesizer.py", line 99, in sample
    rows, root_combination = build_table(
  File "C:\Python310\lib\site-packages\syndiffix\clustering\stitching.py", line 381, in build_table
    acc = _stitch(materialize_tree, forest, metadata, acc, derived_cluster)
  File "C:\Python310\lib\site-packages\syndiffix\clustering\stitching.py", line 372, in _stitch
    return _do_stitch(forest, metadata, left, right, derived_cluster)
  File "C:\Python310\lib\site-packages\syndiffix\clustering\stitching.py", line 300, in _do_stitch
    raise ValueError(f"Empty sequence in cluster {right_combination}.")
ValueError: Empty sequence in cluster (0, 2).
```

**Comment by edongashi** [comment]
How do we get a cluster `(0, 2)` if we have 2 columns? Something weird must be going on...

**Comment by edongashi** [comment]
I think your code is creating 200 columns and 2 rows, which are being suppressed.

**Comment by cristianberneanu** [comment]
Yeah, that make sense in explaining the crash. But we should stil fix the bug.
