### ISSUE TITLE
Hitting a problem with bloom filter size

### ISSUE THREAD

**Issue by yoid2000** [diffix/syndiffix#63]
This error happens when running with an AID column. The specific case here is for the `taxi` table. The aid column is `hack`. I ran with 10000 rows. I tried several different data dataframes. Two had one column (`med` and `passenger_count`). And one had two columns (start and end datetime). All failed like this.

```
Fitting the synthesizer over the data...
c:\paul\GitHub\syndiffix-py\syndiffix\forest.py:62: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  self.aid_data: npt.NDArray[np.uint64] = aids.applymap(hash_aid).to_numpy(Hash)
Traceback (most recent call last):
  File "C:\paul\GitHub\misc\python\syndiffix-py-play\testSynDiffixPy.py", line 120, in <module>
    tsd = testSynDiffixPy(df, csvFile, ['med','hack'], output_dir, aidsColumns=aidsColumns)
  File "C:\paul\GitHub\misc\python\syndiffix-py-play\testSynDiffixPy.py", line 55, in __init__
    synthesizer = Synthesizer(self.dfOrig, aids=aids)
  File "c:\paul\GitHub\syndiffix-py\syndiffix\synthesizer.py", line 46, in __init__
    self.forest = Forest(
  File "c:\paul\GitHub\syndiffix-py\syndiffix\forest.py", line 75, in __init__
    tree = self._build_tree(combination).push_down_1dim_root()
  File "c:\paul\GitHub\syndiffix-py\syndiffix\forest.py", line 120, in _build_tree
    tree = tree.add_row(0, RowId(index))
  File "c:\paul\GitHub\syndiffix-py\syndiffix\tree.py", line 221, in add_row
    self._create_child_leaf(child_index, row) if child is None else child.add_row(depth + 1, row)
  File "c:\paul\GitHub\syndiffix-py\syndiffix\tree.py", line 223, in add_row
    self.update_aids(row)
  File "c:\paul\GitHub\syndiffix-py\syndiffix\tree.py", line 50, in update_aids
    self.entity_counter.add(self.context.aid_data[row])
  File "c:\paul\GitHub\syndiffix-py\syndiffix\counters.py", line 43, in add
    self.aid_sets[i].add(aid)
  File "C:\Users\local_francis\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pybloom_live\pybloom.py", line 141, in add
    raise IndexError("BloomFilter is at capacity")
IndexError: BloomFilter is at capacity
PS C:\paul\GitHub\misc\python\syndiffix-py-play>
```

**Comment by cristianberneanu** [comment]
The bloom-filter library that we are using considers the provided `capacity` as the maximum possible capacity (and it raises an error when full), instead of looking at it as an estimated capacity (above which accuracy would start to drop below the provided target error rate).

Since it doesn't suit our needs, we can either replace it or drop this optimization.
I prefer the latter, since the rest of the code is so slow that I don't think this buys us much.

**Comment by yoid2000** [comment]
Ok let's drop for now
