### ISSUE TITLE
list index out of range when building microdata

### ISSUE THREAD

**Issue by edongashi** [diffix/syndiffix#64]
```
Model sdx_py
Using source file census.csv
Model sdx_py for dataset /INS/syndiffix/work/edon/results/sdx_py/csv/train/census.csv, focus column detailed household summary in household
Training dataframe shape (before features) (209499, 41)
['age', 'class of worker', 'detailed industry recode', 'detailed occupation recode', 'education', 'wage per hour', 'enroll in edu inst last wk', 'marital stat', 'major industry code', 'major occupation code', 'race', 'hispanic origin', 'sex', 'member of a labor union', 'reason for unemployment', 'full or part time employment stat', 'capital gains', 'capital losses', 'dividends from stocks', 'tax filer stat', 'region of previous residence', 'state of previous residence', 'detailed household and family stat', 'detailed household summary in household', 'migration code-change in msa', 'migration code-change in reg', 'migration code-move within reg', 'live in this house 1 year ago', 'migration prev res in sunbelt', 'num persons worked for employer', 'family members under 18', 'country of birth father', 'country of birth mother', 'country of birth self', 'citizenship', 'own business or self employed', "fill inc questionnaire for veteran's admin", 'veterans benefits', 'weeks worked in year', 'year', 'label']
Columns ['age', 'class of worker', 'detailed industry recode', 'detailed occupation recode', 'education', 'wage per hour', 'enroll in edu inst last wk', 'marital stat', 'major industry code', 'major occupation code', 'race', 'hispanic origin', 'sex', 'member of a labor union', 'reason for unemployment', 'full or part time employment stat', 'capital gains', 'capital losses', 'dividends from stocks', 'tax filer stat', 'region of previous residence', 'state of previous residence', 'detailed household and family stat', 'detailed household summary in household', 'migration code-change in msa', 'migration code-change in reg', 'migration code-move within reg', 'live in this house 1 year ago', 'migration prev res in sunbelt', 'num persons worked for employer', 'family members under 18', 'country of birth father', 'country of birth mother', 'country of birth self', 'citizenship', 'own business or self employed', "fill inc questionnaire for veteran's admin", 'veterans benefits', 'weeks worked in year', 'year', 'label']
Running with ML target detailed household summary in household...
Column clusters:
Initial= [6, 7, 9, 10, 11, 12, 23]
Derived= (SHARED, [23], [13, 14, 15, 19, 20, 24])
Derived= (SHARED, [23], [25, 26, 27, 28, 29])
Derived= (SHARED, [23], [0, 37, 39, 40, 30])
Derived= (SHARED, [23], [2, 3, 4, 5])
Derived= (SHARED, [23], [8, 16, 17, 18, 21])
Derived= (SHARED, [23], [32, 33, 38, 22, 31])
Derived= (SHARED, [], [1])
Derived= (SHARED, [], [34])
Derived= (SHARED, [], [35])
Derived= (SHARED, [], [36])
Traceback (most recent call last):
  File "/INS/syndiffix/work/edon/test-syndiffix/test_syndiffix/oneModel.py", line 598, in <module>
    fire.Fire(oneModel)
  File "/home/egashi/.asdf/installs/python/3.10.13/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/egashi/.asdf/installs/python/3.10.13/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/egashi/.asdf/installs/python/3.10.13/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/INS/syndiffix/work/edon/test-syndiffix/test_syndiffix/oneModel.py", line 530, in oneModel
    runSynDiffix(df, outPath, focusColumn, doPatches, testData, job)
  File "/INS/syndiffix/work/edon/test-syndiffix/test_syndiffix/oneModel.py", line 136, in runSynDiffix
    synData = synthesizer.sample()
  File "/INS/syndiffix/work/edon/syndiffix-py/syndiffix/synthesizer.py", line 70, in sample
    rows, root_combination = build_table(
  File "/INS/syndiffix/work/edon/syndiffix-py/syndiffix/clustering/stitching.py", line 377, in build_table
    acc = materialize_tree(forest, clusters.initial_cluster)
  File "/INS/syndiffix/work/edon/syndiffix-py/syndiffix/synthesizer.py", line 62, in materialize_tree
    generate_microdata(
  File "/INS/syndiffix/work/edon/syndiffix-py/syndiffix/microdata.py", line 198, in generate_microdata
    microdata_rows.extend(
  File "/INS/syndiffix/work/edon/syndiffix-py/syndiffix/microdata.py", line 148, in _microdata_row_generator
    yield [_generate(i, c, nm) for i, c, nm in zip(intervals, convertors, null_mappings)]
  File "/INS/syndiffix/work/edon/syndiffix-py/syndiffix/microdata.py", line 148, in <listcomp>
    yield [_generate(i, c, nm) for i, c, nm in zip(intervals, convertors, null_mappings)]
  File "/INS/syndiffix/work/edon/syndiffix-py/syndiffix/microdata.py", line 139, in _generate
    return convertor.from_interval(interval) if interval.min != null_mapping else (None, null_mapping)
  File "/INS/syndiffix/work/edon/syndiffix-py/syndiffix/microdata.py", line 122, in from_interval
    return self._map_interval(interval)
  File "/INS/syndiffix/work/edon/syndiffix-py/syndiffix/microdata.py", line 127, in _map_interval
    min_value = self.value_map[int(interval.min)]
IndexError: list index out of range
```

I think it somehow ended up with an empty set of strings.

**Comment by cristianberneanu** [comment]
It looks like the range with the null values gets overly fragmented and the check for the null mapping fails when generating microdata.
